# Generated by Django 3.0.6 on 2020-06-15 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('room_id', models.IntegerField()),
                ('request_time', models.DateTimeField()),
                ('finish_time', models.DateTimeField()),
                ('request_duration', models.DecimalField(decimal_places=1, max_digits=20)),
                ('fan_speed', models.IntegerField()),
                ('fee_rate', models.DecimalField(decimal_places=1, max_digits=3)),
                ('fee', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'db_table': 'service',
            },
        ),
    ]
